Fixed ipv6 icmp
geerlingguy/ansible-role-firewall pull request #44
Opened 2017-10-13 14:32 UTC by schoeppe

Need ip6tables to accept ipv6-icmp not icmp.

The ip6tables command accepts the argument icmp (because it is a valid protocol in /etc/protocols), but the icmp protocol does not make sense in a ipv6 chain. You want ipv6-icmp instead!

This could lead to some hard to find bugs in dual stacked networks.

2019-07-29 06:10 UTC, hellerbarde commented
is "ipv6-icmp" the same as "icmpv6"

2019-07-29 08:09 UTC, schoeppe commented
I am using the term ipv6-icmp because it is written like that in /etc/protocols and in iptables rules.
The official term is ICMPv6 I think - so the answer is yes.

2019-07-29 08:23 UTC, hellerbarde commented
I just mentioned it, because I also ran into this issue, but for me to make it work, I had to enter `icmpv6` in the rule. See https://github.com/hellerbarde/ansible-role-firewall/commit/6e3bc35d810d3cd4928214972e2eea7198c64df4

2019-07-29 08:37 UTC, schoeppe commented
I see.

As `icmpv6` is accepted by iptables as a protocol and it does not depend on /etc/protocols it may be even better to use this as the protocol name.

2019-07-29 11:18 UTC, hellerbarde commented
> As `icmpv6` is accepted by iptables as a protocol and it does not depend on /etc/protocols it may be even better to use this as the protocol name.

I'd say so as well, it's the name mentioned in the man page (https://linux.die.net/man/8/ip6tables)

2019-10-11 06:22 UTC, emq commented
Thanks @schoeppe for pointing that out!

I noticed that without the fix ipv6 neighbor discovery was broken on fresh hetzner node, took me a while to realize wtf is going on 😅

2020-01-27 16:04 UTC, hellerbarde commented
@geerlingguy Can you please merge this and release it on ansible-galaxy? That would be very helpful.

2020-01-27 16:38 UTC, geerlingguy requested changes

2020-01-27 16:38 UTC, geerlingguy commented on defaults/main.yml
> -  - "25"
I'd rather limit this PR to just fixing the ip6tables ping command.

2020-01-27 17:37 UTC, merged

2020-01-27 17:39 UTC, geerlingguy commented
This is in 2.4.3 — thanks again!

2020-01-29 10:23 UTC, hellerbarde commented
Thanks a lot! *removes manual patch in company tooling* ;)